### PR TITLE
Task8

### PR DESCRIPTION
**Pull request by chermic**
EVALUATION CRITERIA:
1 - Dockerfile is prepared, image is building. Image size is minimised to be less than 500 MB.
2 - Dockerfile is optimized. Files that change more often and commands that depend on them should be included later, files and commands that change less should be at the top.
3 - Folders are added to .dockerignore, with explanations. At least 2 big directories should be excluded from build context. Elastic Beanstalk application is initialized.
4 - Environment is created and the app is deployed to the AWS cloud. You must provide a link to your GitHub repo with Cart API service or PR with created Dockerfile and related configurations.
5 - FE application is updated with Cart API endpoint. You must provide a PR with updates in your FE repository and OPTIONALLY link to deployed front-end app which makes proper API calls to your Cart service.

FE PR: https://github.com/chermic/nodejs-aws-fe/pull/5
FE app: https://d3l9zqe2490dzq.cloudfront.net

### CODE REVIEW

**Comment by evgeny-romanov-epam** [comment]
You need  to use https urls for API

**Comment by chermic** [comment]
> You need to use https urls for API
Why? I can't find this point in task

**Comment by evgeny-romanov-epam** [comment]
> > You need to use https urls for API
> 
> Why? I can't find this point in task

Because when you try to add something to a cart with a link you provided you get an error:

xhr.js:178 Mixed Content: The page at 'https://d3l9zqe2490dzq.cloudfront.net/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://chermic-cart-api-dev.eu-west-1.elasticbeanstalk.com/api/profile/cart'. This request has been blocked; the content must be served over HTTPS.

**Comment by maksumov** [comment]
> > > You need to use https urls for API
> > 
> > 
> > Why? I can't find this point in task
> 
> Because when you try to add something to a cart with a link you provided you get an error:
> 
> xhr.js:178 Mixed Content: The page at 'https://d3l9zqe2490dzq.cloudfront.net/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://chermic-cart-api-dev.eu-west-1.elasticbeanstalk.com/api/profile/cart'. This request has been blocked; the content must be served over HTTPS.

I also encountered a misunderstanding about the necessity of an https url of the cart api. 

I asked a question to our colleagues in the discord (#cross-check-aws) and they decided:
1. not lowering the score for the absence of https urls 
2. check the work by disabling the blocking of mixed content in the browser.

**Review by maksumov — APPROVED** [review]

**Pull request merged**
